### ISSUE TITLE
Process opens, but no window

### ISSUE THREAD

**Issue by zmalsberg** [Maldela/fancontrol-gui#18]
Installed all dependencies, including kirigami2-dev, installed fancontrol-gui using the 'git clone' example, can see the icon in the start menu, clicking does nothing, console says fancontrol-gui not found.
Though I can see fancontrol-gui running in the background in qps process viewer. This is on Lubuntu 18.10.

**Comment by Maldela** [comment]
Try fancontrol_gui in console.

**Comment by subterfugium** [comment]
Same here ubuntu 18.04 and git clone method:
user@pc:~/Git/fancontrol-gui/build$ fancontrol_gui 
"file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/Application.qml" 
 "Error loading QML file.\n23: module \"QtQuick.Dialogs\" version 1.3 is not installed\n"

**Comment by subterfugium** [comment]
Thanks.

Now:
"file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/Application.qml" 
 "Error loading QML file.\n90: Type SensorsTab unavailable\n24: module \"org.kde.kirigami\" version 2.4 is not installed\n"

**Comment by Maldela** [comment]
Try installing qml-module-org-kde-kirigami2.

**Comment by Maldela** [comment]
I've also reduced the required kirigami version to 2.0 just now.

**Comment by subterfugium** [comment]
qml-module-org-kde-kirigami2 was already installed. After git pull and new build fancontrol_gui opened. I will try it later this week.  Thanks.

**Comment by Maldela** [comment]
Have you tried the "Detect Fans" button next to the fan selector?

**Comment by subterfugium** [comment]
Yeah, I tried that. I have another PC running manjaro where I installed fancontrol_gui-git from AUR. There everything works fine, but BIOS has "Normal" mode for fans. In this ubuntu PC, bios has "Smart Fan Control" which can be disabled and I tried that, but all fans still run 100% rpm even if I try to use fancontrol_gui in Ubuntu. It's very hard to say if it's issue in motherboard in this Ubuntu PC or fancontrol. Fans are detected atleast by sensors-detect and psensor as well as fancontrol_gui.

Anyway, I am able to launch fancontrol_gui now on my ubuntu, maybe someone else can actually verify that it's working on ubuntu :)

**Comment by Maldela** [comment]
All the button does is to run `sudo sensors-detect --auto`. Maybe your mainboard just doesn't play nice with lm_sensors.

**Comment by IanRawz** [comment]
I'm having the same issue. GUI won't open after clicking on the icon, but the process seems to be running.
Running fancontrol_gui in terminal shows this error:
```
"file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/Application.qml" 
 "Error loading QML file.\n194: Cannot assign to non-existent property \"onApplied\"\n"
```

**Comment by Maldela** [comment]
The applied signal was introduced in Qt 5.10. I changed it to use the accepted signal. Should work now with Qt 5.8 and higher.

**Comment by IanRawz** [comment]
Thanks for the quick update!
Sadly now I'm getting this error:
```
"file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/Application.qml" 
 "Error loading QML file.\n189: Cannot assign to non-existent property \"onDiscarded\"\n"
```

**Comment by Maldela** [comment]
A closer look at the documentation revealed that all the useful signals need Qt 5.10 or higher. I removed the dialog until I'm ready to bump the dependency.

**Comment by gerion0** [comment]
I also have this problem (roughly). I did not install fancontrol_gui but only execute the binary in `./bin/fancontrol_gui` within the build directory.

The output is:
```
% ./bin/fancontrol_gui
File name empty!

```
The process does not end there but also doesn't do anything visible.

Using GDB and pressing ctrl-c when the process seems to hang gives this stacktrace:
```
#0  0x00007ffff5f2ab3e in poll () at /lib64/libc.so.6
#1  0x00007ffff467cdbe in g_main_context_iterate.isra () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff467cefe in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff66b57ed in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff665d1cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff6665471 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x000055555555a1d2 in main(int, char**) (argc=1, argv=0x7fffffffc828) at ../fancontrol-gui/src/main.cpp:116
```
If you need additional info, please say so. I have the fancontrol server already running (`/usr/sbin/fancontrol`). Stopping it do not help.

I'm on Gentoo with KDE.

**Comment by qiray** [comment]
@gerion0, I had the same issue. But I installed the app with:
```bash
sudo make install
``` 
And now it works. Maybe it requires some system dependencies so it doesn't work without installation.
